### ISSUE TITLE
Create Reusable Components

### ISSUE THREAD

**Issue by wardVD** [kubeflow/website#1826]
https://www.kubeflow.org/docs/pipelines/sdk/component-development/

program.py doesn't work, suggested change:

```#!/usr/bin/env python3
import argparse
from pathlib import Path


# Function doing the actual work (Outputs first N lines from a text file)
def do_work(input1_file, output1_file, param1):
    for line in input1_file.readlines()[:param1]:
        if not line:
            break
        _ = output1_file.write(line)


# Defining and parsing the command-line arguments
parser = argparse.ArgumentParser(description='My program description')
parser.add_argument('--input1-path', type=str,
                    help='Path of the local file containing the Input 1 data.')  # Paths should be passed in, not hardcoded
parser.add_argument('--param1', type=int, default=100, help='Parameter 1.')
parser.add_argument('--output1-path', type=str,
                    help='Path of the local file where the Output 1 data should be written.')  # Paths should be passed in, not hardcoded
args = parser.parse_args()

# Creating the directory where the output file will be created (the directory may or may not exist).
Path(args.output1_path).parent.mkdir(parents=True, exist_ok=True)

with open(args.input1_path, 'r') as input1_file:
    with open(args.output1_path, 'w') as output1_file:
        do_work(input1_file, output1_file, args.param1)
```

**Comment by janeman98** [comment]
/assign

Original program.py will give the following error when number of line request is more than the actual number of line in the input file:

`Traceback (most recent call last):
  File "program.py", line 27, in <module>
    do_work(input1_file, output1_file, args.param1)
  File "program_old.py", line 8, in do_work
    line = next(input1_file)
StopIteration`
