### ISSUE TITLE
Updates TFJob and PytorchJob document to disable istio sidecar inject

### ISSUE THREAD

**Issue by shawnzhu** [kubeflow/website#2011]
## Problem

YAML resource description from this article doesn't work: https://www.kubeflow.org/docs/components/training/tftraining/#what-is-tfjob

So as that from https://www.kubeflow.org/docs/components/training/pytorch/#monitoring-a-pytorch-job

It leads to several issue reports including: 

* https://github.com/kubeflow/pytorch-operator/issues/258
* https://github.com/kubeflow/katib/issues/1042
* https://github.com/kubeflow/kubeflow/issues/4935

## Solution

So adding one annotation `sidecar.istio.io/inject: "false"` will get the examples work in above two articles. But it would need some note like what's expected from https://github.com/kubeflow/kubeflow/issues/4935

**Comment by shawnzhu** [comment]
Given `tfjob` example, the pods will be in `Error` status when following the doc because of this problem:

```
 kubectl logs dist-mnist-for-e2e-test-ps-0 -n <my-profile-name> -c tensorflow
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/var/tf_dist_mnist/dist_mnist.py", line 303, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/var/tf_dist_mnist/dist_mnist.py", line 110, in main
    mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 240, in read_data_sets
    source_url + TRAIN_IMAGES)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download
    temp_file_name, _ = urlretrieve_with_retry(source_url)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry
    return urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 101] Network is unreachable
```

This is an effect of ISTIO sidecar auto-injection. With https://github.com/kubeflow/kubeflow/issues/4935#issuecomment-615256808, I suggest disabling istio sidecar inject to get the examples to work while documenting impacts like missing security feature on tfjob when side car inject is disabled.

**Comment by jinchihe** [comment]
@shawnzhu Make sense, or is that better to add this in Troubleshooting for this?

**Comment by shawnzhu** [comment]
> is that better to add this in Troubleshooting for this?

Yes only the design is TFJob/PyTorchJob works with Istio sidecar inject enabled namespace/profile (required by kubeflow). Then we can troubleshoot by disabling sidecar inject.

**Comment by shawnzhu** [comment]
Close since it has been fixed on latest doc: https://master.kubeflow.org/docs/components/training/tftraining/ and the code example: https://github.com/kubeflow/pytorch-operator/blob/eba73411bc03d70b72dcab623aa7a01c14f811d4/examples/mnist/v1/pytorch_job_mnist_gloo.yaml
